package com.hss01248.basewebview.history.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BROWSER_HISTORY_INFO".
*/
public class BrowserHistoryInfoDao extends AbstractDao<BrowserHistoryInfo, String> {

    public static final String TABLENAME = "BROWSER_HISTORY_INFO";

    /**
     * Properties of entity BrowserHistoryInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Url = new Property(0, String.class, "url", true, "URL");
        public final static Property IsCollect = new Property(1, int.class, "isCollect", false, "IS_COLLECT");
        public final static Property IconUrl = new Property(2, String.class, "iconUrl", false, "ICON_URL");
        public final static Property UpdateTime = new Property(3, long.class, "updateTime", false, "UPDATE_TIME");
        public final static Property ViewTimes = new Property(4, long.class, "viewTimes", false, "VIEW_TIMES");
        public final static Property Title = new Property(5, String.class, "title", false, "TITLE");
        public final static Property Group = new Property(6, String.class, "group", false, "GROUP");
        public final static Property HasSynced = new Property(7, int.class, "hasSynced", false, "HAS_SYNCED");
    }


    public BrowserHistoryInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BrowserHistoryInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BROWSER_HISTORY_INFO\" (" + //
                "\"URL\" TEXT PRIMARY KEY NOT NULL ," + // 0: url
                "\"IS_COLLECT\" INTEGER NOT NULL ," + // 1: isCollect
                "\"ICON_URL\" TEXT," + // 2: iconUrl
                "\"UPDATE_TIME\" INTEGER NOT NULL ," + // 3: updateTime
                "\"VIEW_TIMES\" INTEGER NOT NULL ," + // 4: viewTimes
                "\"TITLE\" TEXT," + // 5: title
                "\"GROUP\" TEXT," + // 6: group
                "\"HAS_SYNCED\" INTEGER NOT NULL );"); // 7: hasSynced
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_BROWSER_HISTORY_INFO_UPDATE_TIME ON \"BROWSER_HISTORY_INFO\"" +
                " (\"UPDATE_TIME\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BROWSER_HISTORY_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BrowserHistoryInfo entity) {
        stmt.clearBindings();
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(1, url);
        }
        stmt.bindLong(2, entity.getIsCollect());
 
        String iconUrl = entity.getIconUrl();
        if (iconUrl != null) {
            stmt.bindString(3, iconUrl);
        }
        stmt.bindLong(4, entity.getUpdateTime());
        stmt.bindLong(5, entity.getViewTimes());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String group = entity.getGroup();
        if (group != null) {
            stmt.bindString(7, group);
        }
        stmt.bindLong(8, entity.getHasSynced());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BrowserHistoryInfo entity) {
        stmt.clearBindings();
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(1, url);
        }
        stmt.bindLong(2, entity.getIsCollect());
 
        String iconUrl = entity.getIconUrl();
        if (iconUrl != null) {
            stmt.bindString(3, iconUrl);
        }
        stmt.bindLong(4, entity.getUpdateTime());
        stmt.bindLong(5, entity.getViewTimes());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String group = entity.getGroup();
        if (group != null) {
            stmt.bindString(7, group);
        }
        stmt.bindLong(8, entity.getHasSynced());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public BrowserHistoryInfo readEntity(Cursor cursor, int offset) {
        BrowserHistoryInfo entity = new BrowserHistoryInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // url
            cursor.getInt(offset + 1), // isCollect
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // iconUrl
            cursor.getLong(offset + 3), // updateTime
            cursor.getLong(offset + 4), // viewTimes
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // title
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // group
            cursor.getInt(offset + 7) // hasSynced
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BrowserHistoryInfo entity, int offset) {
        entity.setUrl(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setIsCollect(cursor.getInt(offset + 1));
        entity.setIconUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUpdateTime(cursor.getLong(offset + 3));
        entity.setViewTimes(cursor.getLong(offset + 4));
        entity.setTitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setGroup(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setHasSynced(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final String updateKeyAfterInsert(BrowserHistoryInfo entity, long rowId) {
        return entity.getUrl();
    }
    
    @Override
    public String getKey(BrowserHistoryInfo entity) {
        if(entity != null) {
            return entity.getUrl();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BrowserHistoryInfo entity) {
        return entity.getUrl() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
