package com.hss01248.basewebview.history.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hss01248.basewebview.history.db.BrowserHistoryInfo;

import com.hss01248.basewebview.history.db.BrowserHistoryInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig browserHistoryInfoDaoConfig;

    private final BrowserHistoryInfoDao browserHistoryInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        browserHistoryInfoDaoConfig = daoConfigMap.get(BrowserHistoryInfoDao.class).clone();
        browserHistoryInfoDaoConfig.initIdentityScope(type);

        browserHistoryInfoDao = new BrowserHistoryInfoDao(browserHistoryInfoDaoConfig, this);

        registerDao(BrowserHistoryInfo.class, browserHistoryInfoDao);
    }
    
    public void clear() {
        browserHistoryInfoDaoConfig.clearIdentityScope();
    }

    public BrowserHistoryInfoDao getBrowserHistoryInfoDao() {
        return browserHistoryInfoDao;
    }

}
