package com.hss01248.history.api.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hss01248.history.api.SearchHistoryItem;

import com.hss01248.history.api.db.SearchHistoryItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryItemDaoConfig;

    private final SearchHistoryItemDao searchHistoryItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryItemDaoConfig = daoConfigMap.get(SearchHistoryItemDao.class).clone();
        searchHistoryItemDaoConfig.initIdentityScope(type);

        searchHistoryItemDao = new SearchHistoryItemDao(searchHistoryItemDaoConfig, this);

        registerDao(SearchHistoryItem.class, searchHistoryItemDao);
    }
    
    public void clear() {
        searchHistoryItemDaoConfig.clearIdentityScope();
    }

    public SearchHistoryItemDao getSearchHistoryItemDao() {
        return searchHistoryItemDao;
    }

}
